### PR TITLE
Extract UI related config params into a UIConfig type

### PR DESCRIPTION
**Pull request by saurabhnanda**
### Problem

1. `Config{..}` type was mixing up config params required for the job-runner along with the config params required for the web-UI.
2. There are cases where we want to start job-runners independently of the web-ui (typically you will only have one instance of the web-ui, whereas you may have multiple instances of the job-runner on different machines)
3. The mixing-up of these two concerns in the `Config{..}` type forces one to define unnecessary config params if only the web-ui needs to be started or only the job-runner needs to be started

#### Sub-problem

- The callback-within-callback style of `OddJobs.Cli` is very confusing. It was confusing even for me when I wanted to write a custom CLI for some purpose.

### Solution

1. Introduced `Types.UIConfig{..}`
2. Introduced `Cli.CliType` that allows one to easily start only the job-runner, only the web-ui, or both.
3. `OddJobs.Cli` parses the command-line and builds a `Config -> Config` (or `UIConfig -> UIConfig`) function that overrides the default config based on command-line arguments. This function can be passed to `mkConfig` or `mkUIConfig`. This avoid the "callback-withing-callback" style to some extent.

### CODE REVIEW

**Comment by saurabhnanda** [comment]
@tfausak @kanagarajkm @jappeace @ivb-supercede leomayleomay @mrputty @aschmois this is a moderately large breaking change. Please share  your thoughts about this.

**Comment by tfausak** [comment]
I haven't looked at the changes too closely, but it all sounds good to me and we should be able to adapt to these changes.

**Comment by kanagarajkm** [comment]
@saurabhnanda we don't use the webui and don't fiddle with any config. changes should be fine for us.

**Comment by ivb-supercede** [comment]
Sounds good to me.

**Pull request merged**
