### PR TITLE
Support aeson-2.2.0.0

### PR DESCRIPTION
**Pull request by ilyakooo0**
I'm not sure if you want this change made in this way, but I needed aeson-2.2.0.0.

### CODE REVIEW

**Comment by jappeace** [comment]
I don't mind, however please not the CI issues. This is likely cuased by allow newer and/or enabling nix.

**Comment by tchoutri** [comment]
@ilyakooo0 Do you need any help bringing this to the finish line?

**Comment by ilyakooo0** [comment]
@tchoutri feel free to duplicate this PR. I an not planning to work on this in the near future.

**Comment by jappeace** [comment]
merged in https://github.com/saurabhnanda/odd-jobs/pull/102

**Pull request closed without merging**
